// Naru dispatch plugin: generates model-class variants and configured MCP policy.
//
// Reads runtime policy from naru-runtime.json and, in the
// config hook, clones the base subagents into hidden variants with the
// class's model and effort baked in (naru-reader-<class>, ...). The
// orchestrator dispatches them through OpenCode's native task tool, so the
// TUI's subagent rendering and click-through behave exactly as they do for
// the base agents. Its opt-in MCP pass reads only merged server names and
// enabled states. The plugin hooks config only — no tools, no events, no
// session access — and policy synthesis is atomic.
import { fileURLToPath } from 'node:url';
import {
    applyDispatchToConfigAtomically,
    applyReviewDefaultsToConfig,
    buildReviewDefaultsAppendix,
    parseModelsConfig,
    readAuthProviders,
} from '../tools/naru-lib/dispatch.mjs';
import type { ModelsConfig } from '../tools/naru-lib/dispatch.mjs';
import { globalRuntimeConfigPath, loadRuntimeConfigLayers, type RuntimeConfig } from '../tools/naru-lib/runtime-config.mjs';

interface OpenCodeAgentConfig {
    [key: string]: unknown;
}

interface OpenCodeConfig {
    agent?: Record<string, OpenCodeAgentConfig>;
    mcp?: unknown;
    [key: string]: unknown;
}

interface OpenCodePluginHooks {
    config(config: OpenCodeConfig): Promise<void>;
}

const CONFIG_PATH = fileURLToPath(new URL('../naru-runtime.json', import.meta.url));
export interface NaruDispatchPluginOptions {
    globalRuntimePath?: string;
    localRuntimePath?: string;
    authProviders?: ReadonlySet<string> | null;
}

export const NaruDispatchPlugin = async (): Promise<OpenCodePluginHooks> => {
    return createNaruDispatchPlugin();
};

export async function createNaruDispatchPlugin(options: NaruDispatchPluginOptions = {}): Promise<OpenCodePluginHooks> {
    let runtime: RuntimeConfig | null = null;
    try {
        runtime = await loadRuntimeConfigLayers([
            options.globalRuntimePath ?? globalRuntimeConfigPath(),
            options.localRuntimePath ?? CONFIG_PATH,
        ]);
    }
    catch {
        // Invalid layers fail closed in the hook below. In a combined global
        // and project load this also removes rules generated by an earlier hook.
    }
    let classes: ModelsConfig = {};
    try {
        classes = runtime ? parseModelsConfig(runtime.models) : {};
    }
    catch {
        // Invalid model classes must not prevent the base agents or review
        // defaults from loading.
    }
    const authProviders = Object.hasOwn(options, 'authProviders') ? options.authProviders : readAuthProviders();
    return createNaruDispatchHooks(runtime, classes, authProviders);
}

export function createNaruDispatchHooks(runtime: RuntimeConfig | null, classes: ModelsConfig, authProviders: ReadonlySet<string> | null | undefined): OpenCodePluginHooks {
    return {
        config: async (config: OpenCodeConfig) => {
            if (!runtime) {
                try {
                    applyDispatchToConfigAtomically(config, {}, authProviders, 'off', config.mcp);
                }
                catch {
                    // A broken agent map remains untouched.
                }
                return;
            }
            try {
                const prompt = config.agent?.['naru-orchestrator']?.prompt;
                if (typeof prompt !== 'string' || !prompt.includes(buildReviewDefaultsAppendix(runtime.review))) {
                    applyReviewDefaultsToConfig(config, runtime.review);
                }
            }
            catch {
                // Review configuration does not depend on model dispatch.
            }
            try {
                applyDispatchToConfigAtomically(config, classes, authProviders, runtime.mcp.configuredTools, config.mcp);
            } catch {
                // Broken routing or MCP policy synthesis leaves the independently
                // applied review defaults intact and all other agent state unchanged.
            }
        },
    };
}
